### PR TITLE
Tools & shield rework

### PR DESCRIPTION
**Pull request by NoahTheLegend**
Added a chat command `!addknight u8` from 1 to 8
Spawns a passive knight with rotated shield
Added a flat map for testing
Shielding to top corners doesn't block underhits

### CODE REVIEW

**Comment by Snikerss** [comment]
Shielding to top corners doesn't block underhits is bad, then overhead jabs will bee too op

**Comment by NoahTheLegend** [comment]
they wont. Just catch the timings. Current shielding to top corners is equal to side shielding but better, because you also cover your head.

**Comment by Snikerss** [comment]
Just tested it, so if player keep shield on top corner u are able to hit him from below, and if shield is left or right u can hit him overhead thats too abusive, with it no way to be safe from jab spam, timings about u talking is impossible.

**Comment by Snikerss** [comment]
if u add covering head with ordinary horizontal shielding then i will merge it

**Comment by NoahTheLegend** [comment]
what will be the point of shielding to top corners then? i thought it IS supposed to be covering head state, but sacrificing legs covering
I repeat, vanilla shielding to corner is equal to side shielding, but additionally you get head-hit protection

**Comment by Snikerss** [comment]
i know it, and i repeat you that in game realities jab spam will become too op, what u will do with it then?

**Pull request closed without merging**
